### ISSUE TITLE
Reduce / Disable Logging from mongod?

### ISSUE THREAD

**Issue by lcalisi** [kaizendorks/pymongo_inmemory#28]
Is there a way to disable (or reduce) logging from mongod? Our test cases are overwhelmed from the server output? We locally patch the file and add "--syslog" to the startup options in https://github.com/kaizendorks/pymongo_inmemory/blob/master/pymongo_inmemory/mongod.py#L93

**Comment by ekarademir** [comment]
I'm not sure if there is a way, but if that solution works for you, I can create a solution around that. Thanks for letting us know! 

Of course if you can think of a solution we are open to PRs.

**Comment by lcalisi** [comment]
It does work in my local mod by adding that flag.

**Comment by lcalisi** [comment]
Thank you. This change is working well.
