### ISSUE TITLE
Complete GitHub community checklist

### ISSUE THREAD

**Issue by ekarademir** [kaizendorks/pymongo_inmemory#31]
Missing bits are listed here:
https://github.com/kaizendorks/pymongo_inmemory/community

### Acceptance Criteria
* At least code of conduct and issue report templates are complete.

**Comment by morrme** [comment]
The content reports have to be done by an admin: https://docs.github.com/en/github/building-a-strong-community/managing-reported-content-in-your-organizations-repository

Next would be the PR template. It depends on the contributor guidelines, so you may want to do that first. 

The PR template can then welcome the contributor, remind them of your guidelines and your code of conduct, and include any other requirements you may have before a PR can be submitted.

**Comment by ekarademir** [comment]
@morrme Thank you for the input. I was struggling to understand what "Repository admins accept content reports" setting really meant. I've now enabled it. There is a bit of guideline in the readme but here should be a separate page.
