### ISSUE TITLE
[Question] the downloader of the mongo version in the new realiaze is realy necessary?

### ISSUE THREAD

**Issue by leonardoleanodev** [kaizendorks/pymongo_inmemory#44]
It is a good practice to download into the init some packages to make the libary work it sould not be bether to put it into the all package? Why did you (@ekarademir) put that into the __init__?

**Comment by ekarademir** [comment]
The downloader has been refactored recently, previously it was just a file, and now it's a module. I had to refactor other parts into some decent shape and simply didn't have time to refactor everything. It looks strange but the reason is, basically, historic.

**Comment by ekarademir** [comment]
I think the question is answered. At this point I think module level implementation has some merits.
