### ISSUE TITLE
boolean environment variables not parsed correctly

### ISSUE THREAD

**Issue by rkingsbury** [kaizendorks/pymongo_inmemory#82]
**Describe the bug**

Setting `PYMONGOIM__USE_LOCAL_MONGOD` to either `True` or `False` results in the log message

```
WARNING - Using local mongod instance
```

This occurs because the variable, whether set to `True` or `False`, is parsed as a string by `os.environ.get` at[ this line](https://github.com/kaizendorks/pymongo_inmemory/blob/b2eec6041ca61f4b63a634049ce713b91f296519/pymongo_inmemory/mongod.py#L82), leading to the unexpected behavior that _any attempt_ by the user to set this variable will result in it being evaluated to `True`.

**To Reproduce**

```bash
export PYMONGOIM__USE_LOCAL_MONGOD=False
python
>>> import os
>>> os.environ.get('PYMONGOIM__USE_LOCAL_MONGOD')
'False'
>>> not os.environ.get('PYMONGOIM__USE_LOCAL_MONGOD')
False
```

**Comment by ekarademir** [comment]
This is a very nice catch and a lesson I keep forgetting. It should have been a string comparison to `'true'`.

**Comment by rkingsbury** [comment]
A similar problem may apply to `PYMONGOIM__MONGO_VERSION` which I believe is parsed to a string instead of a numeric value

**Comment by ekarademir** [comment]
> A similar problem may apply to `PYMONGOIM__MONGO_VERSION` which I believe is parsed to a string instead of a numeric value

For this `str` is fine, because this value is being parsed into `SemVer` down the line, hence, value provided can include dots.
