### ISSUE TITLE
stdout overwhelmed by port status messages in CI testing

### ISSUE THREAD

**Issue by rkingsbury** [kaizendorks/pymongo_inmemory#83]
**Describe the bug**

When running in a GitHub actions CI environment with a non default port `27019`, the stdout is flooded with messages like this one

```
PYMONGOIM_MONGOD - WARNING - Using Mongod port set by user: 27019
```

which appear to fire multiple times per second. See example run [here](https://github.com/materialsproject/maggma/actions/runs/6102509934/job/16561145907?pr=846).

Is there way to suppress these messages?

**Context:**
 - OS: [e.g. ubuntu]
 - Version of pymongo_inmemory [e.g. 0.3.0]

Flagging #29 as possibly related

**Comment by ekarademir** [comment]
I'll do a release in few mins, please feel free to reopen if the issue persists. I just removed the log line, since it's no longer necessary as we are advertising the user set config items with the context.
