### ISSUE TITLE
Click used in internal tooling published to pypi

### ISSUE THREAD

**Issue by pbsds** [kaizendorks/pymongo_inmemory#86]
It seems like `click` is [only a dev dependency](https://github.com/kaizendorks/pymongo_inmemory/blob/5ee786d266c40f29211c646030b49688ec613004/pyproject.toml#L44), but you import it in [user-facing endpoints](https://github.com/kaizendorks/pymongo_inmemory/blob/5ee786d266c40f29211c646030b49688ec613004/pymongo_inmemory/downloader/check_urls.py#L10). I think it should it be moved to `[tool.poetry.dependencies]`

**Comment by ekarademir** [comment]
URL checking is not used by the library itself. It's an internal tool. I.e. [MongoD](https://github.com/kaizendorks/pymongo_inmemory/blob/5ee786d266c40f29211c646030b49688ec613004/pymongo_inmemory/mongod.py) doesn't use it, or its imports don't use it either.

Its place is under downloader as convenience, but I can move it to somewhere else.
